version: '3.8'

services:
  frontend:
    image: ghcr.io/kykisemyen/aivyadminpanel:master
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
