version: '3.8'

services:
  frontend:
    image: ghcr.io/kykisemyen/aivyadminpanel:dev
    ports:
      - "8081:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
